services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appointer
      MYSQL_USER: appointer
      MYSQL_PASSWORD: appointer
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  php-nginx:
    image: webdevops/php-nginx:8.2
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
    volumes:
      - ./:/app
    ports:
      - "8080:80"
    working_dir: /app

volumes:
  mysql_data:
